name: Build and Deploy to Github Pages

on:
  pull_request:
    paths-ignore:
      - "data/**"
      - "cmd/*.go"
      - "README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "data/**"
      - "cmd/*.go"
      - "README.md"

jobs:
  deploy_gh_pages:
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: install and build
        run: make build

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: www.openhomescreen.com
