name: data-puller

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  data_pull:
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: run golang script
        run: make gorun

      - name: commit files to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatically updating data files
